print('Initial list')
lst = [1, [2, 3], 4, [[6, 7]]]
print(lst)
print('\n')
print('Transform 1:')
lst = lst + lst[3].pop(0)
lst.remove(list())
print(lst)
print('Transform 2:')
lst = lst + lst.pop(1)
print(lst)
print('\n')
print('Final - Sort list:')
lst.sort()
print(lst)